name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  dio: ^5.5.0+1
  http: ^1.2.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
